### ISSUE TITLE
Parameter unless failed on Exec Live-update

### ISSUE THREAD

**Issue by kstanley-contec** [halyard/puppet-sysctl#1]
Using puppet 3.8.1, the error occurs because the exec resource does not fully-qualify the path the sysctl.

**Comment by akerl** [comment]
Sorry for the delay in noticing this issue. Are you referring to https://github.com/halyard/puppet-sysctl/blob/master/manifests/entry.pp#L21-L22 ?

**Comment by akerl** [comment]
If I'm understanding correctly, this PR should address this: https://github.com/halyard/puppet-sysctl/pull/2

**Comment by akerl** [comment]
This should be fixed in 2.0.2
